name = "ai-kyosuke"
main = "index.ts"
compatibility_date = "2024-04-01"

# Automatically bundle text files imported with `.md` extension
[[rules]]
type = "Text"
globs = ["**/*.md"]
fallbacks = []

[observability.logs]
enabled = true
invocation_logs = false

[observability.traces]
enabled = false

# Define standard variables (secrets must be uploaded via wrangler secret put)
# [vars]
# You can add non-sensitive environment variables here
