name = "ai-kyosuke"
main = "index.ts"
compatibility_date = "2024-04-01"

# Automatically bundle text files imported with `.md` extension
[[rules]]
type = "Text"
globs = ["**/*.md"]
fallbacks = []
fallthrough = true

[observability.logs]
enabled = true
invocation_logs = false

[observability.traces]
enabled = false

# Define standard variables (secrets must be uploaded via wrangler secret put)
[vars]
APP_URL = "https://ai.kyosuke.dev"
FREEE_CLIENT_ID = "728756541310561"

[[kv_namespaces]]
binding = "GITHUB_KV"
id = "6074644670544a80a9805a8814aeeed9"

[[d1_databases]]
binding = "AI_KYOSUKE_DB"
database_name = "ai_kyosuke"
database_id = "33f25041-0aae-4518-a973-88005841f603"

[[queues.producers]]
binding = "GITHUB_QUEUE"
queue = "ai-kyosuke-github"

[[queues.consumers]]
queue = "ai-kyosuke-github"
max_batch_size = 1
max_batch_timeout = 5
